





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyFileVersion("0.5.3.2")]
 [assembly: AssemblyVersion("0.5.3.2")]
 [assembly: KSPAssembly("LtScience", 0, 5, 3)]
